<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Nodes [

<!ENTITY % NameValue "CDATA">
<!ENTITY % PropType "(I|S|D|L|H|B)">
<!ENTITY % VersionValue "CDATA">

<!ELEMENT Prp (#PCDATA)>
<!ELEMENT Node (Node|Prp)*>
<!ELEMENT Nodes (Node)+>

<!ATTLIST Nodes version CDATA "1">

<!ATTLIST Node name CDATA #REQUIRED>

<!ATTLIST Prp name CDATA #REQUIRED>
<!ATTLIST Prp type CDATA #REQUIRED>
<!ATTLIST Prp value CDATA #REQUIRED>
]>
<Nodes version="1">
	<Node name="root">
		<Node name="n-0">
			<Node name="data">
				<Prp name="d-0" type="D" value="41766.5002048032"/>
			</Node>
			<Prp name="isinteger" type="B" value="0"/>
			<Prp name="length" type="I" value="1"/>
			<Prp name="name" type="S" value="Date&amp;Time"/>
			<Prp name="id" type="S" value="{5C4EF7C7-C2C9-43CB-85AE-66E5E6E35778}"/>
			<Prp name="countertype" type="I" value="4"/>
			<Prp name="color" type="I" value="0"/>
			<Prp name="description" type="S" value=""/>
			<Prp name="columnindex" type="I" value="0"/>
			<Prp name="type" type="I" value="0"/>
		</Node>
		<Node name="stack"/>
		<Node name="message 1">
			<Prp name="unit id" type="I" value="0"/>
			<Prp name="as html" type="B" value="0"/>
			<Prp name="type" type="I" value="2"/>
			<Prp name="message" type="S" value="Log Warning"/>
			<Prp name="line no" type="I" value="47"/>
			<Prp name="priority" type="I" value="300"/>
			<Prp name="remarks" type="S" value=""/>
			<Prp name="child index" type="I" value="-1"/>
			<Prp name="link" type="S" value=""/>
			<Prp name="owner id" type="I" value="-1"/>
			<Prp name="picture" type="S" value=""/>
			<Prp name="id" type="I" value="1"/>
			<Prp name="date" type="D" value="41766.5002035185"/>
		</Node>
		<Node name="message 3">
			<Prp name="unit id" type="I" value="0"/>
			<Prp name="as html" type="B" value="0"/>
			<Prp name="type" type="I" value="7"/>
			<Prp name="message" type="S" value="Log Checkpoint"/>
			<Prp name="line no" type="I" value="49"/>
			<Prp name="priority" type="I" value="300"/>
			<Prp name="remarks" type="S" value=""/>
			<Prp name="child index" type="I" value="-1"/>
			<Prp name="link" type="S" value=""/>
			<Prp name="owner id" type="I" value="-1"/>
			<Prp name="picture" type="S" value=""/>
			<Prp name="id" type="I" value="3"/>
			<Prp name="date" type="D" value="41766.5002036111"/>
		</Node>
		<Node name="units">
			<Prp name="unit 0" type="S" value="{C44C84C5-B1E0-4B86-A425-DA1F48D80FFD}"/>
		</Node>
		<Node name="message 2">
			<Prp name="unit id" type="I" value="0"/>
			<Prp name="as html" type="B" value="0"/>
			<Prp name="type" type="I" value="1"/>
			<Prp name="message" type="S" value="Log Event"/>
			<Prp name="line no" type="I" value="48"/>
			<Prp name="priority" type="I" value="300"/>
			<Prp name="remarks" type="S" value=""/>
			<Prp name="child index" type="I" value="-1"/>
			<Prp name="link" type="S" value=""/>
			<Prp name="owner id" type="I" value="-1"/>
			<Prp name="picture" type="S" value=""/>
			<Prp name="id" type="I" value="2"/>
			<Prp name="date" type="D" value="41766.5002035995"/>
		</Node>
		<Node name="message 4">
			<Prp name="unit id" type="I" value="0"/>
			<Prp name="as html" type="B" value="0"/>
			<Prp name="type" type="I" value="3"/>
			<Prp name="message" type="S" value="Log Error"/>
			<Prp name="line no" type="I" value="50"/>
			<Prp name="priority" type="I" value="300"/>
			<Prp name="remarks" type="S" value=""/>
			<Prp name="child index" type="I" value="-1"/>
			<Prp name="stack beginning" type="I" value="0"/>
			<Prp name="stack end" type="I" value="0"/>
			<Prp name="link" type="S" value=""/>
			<Prp name="owner id" type="I" value="-1"/>
			<Prp name="style" type="I" value="1"/>
			<Prp name="picture" type="S" value="Picture1.png"/>
			<Prp name="id" type="I" value="4"/>
			<Prp name="date" type="D" value="41766.5002048032"/>
		</Node>
		<Node name="message 0">
			<Prp name="unit id" type="I" value="0"/>
			<Prp name="as html" type="B" value="0"/>
			<Prp name="type" type="I" value="0"/>
			<Prp name="message" type="S" value="Log Message"/>
			<Prp name="line no" type="I" value="45"/>
			<Prp name="priority" type="I" value="300"/>
			<Prp name="remarks" type="S" value=""/>
			<Prp name="child index" type="I" value="-1"/>
			<Prp name="link" type="S" value=""/>
			<Prp name="owner id" type="I" value="-1"/>
			<Prp name="picture" type="S" value=""/>
			<Prp name="id" type="I" value="0"/>
			<Prp name="date" type="D" value="41766.5002035069"/>
		</Node>
		<Node name="item 0">
			<Prp name="stacktext" type="S" value="test"/>
			<Prp name="unit id" type="I" value="0"/>
			<Prp name="line no" type="I" value="50"/>
		</Node>
		<Node name="child data"/>
		<Prp name="status" type="I" value="2"/>
		<Prp name="perfcounterslength" type="I" value="1"/>
	</Node>
</Nodes>